name: iOS Builder

on:
  push:
    branches:
      - main

env:
  CMAKE_VERSION: 3.5
  LLVM_VERSION: 15.0.6  

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: checkout main
      uses: actions/checkout@master

    - name: compile ios
      run: |
        bash build.sh -o ios
        
      shell: bash


    - name: print output
      run: |
        ls -lha .

